server:
  port: 8080

langchain4j:
  open-ai:
    chat-model:
      model-name: deepseek-chat
      base-url: https://api.deepseek.com
      api-key: ${DEEP_SEEK_API_KEY}
      log-requests: true
      log-responses: true
    streaming-chat-model:
      model-name: deepseek-chat
      base-url: https://api.deepseek.com
      api-key: ${DEEP_SEEK_API_KEY}
      log-requests: true
      log-responses: true
  zhipu-ai:
    streaming-chat-model:
      base-url: https://api.zhipuai.com
      api-key: ${ZHIPU_AI_API_KEY}
      model-name: glm-5

#启用日志info级别
logging:
  level:
    root: INFO

spring:
  datasource:
    username: root
    password: 200411
    url: jdbc:mysql://localhost:3306/guiguxiaozhi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_memory_db

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
